### ISSUE TITLE
problem at find_library in hello-module

### ISSUE THREAD

**Issue by meslahik** [Akagi201/learning-cmake#5]
Hi,
After hours of trying to build to hello-module project, found that according to the documentation for [find_library](https://cmake.org/cmake/help/cmake2.6docs.html#command:find_library) you need to have PATHS rather than PATH to define additional paths for searching for the libraries.

**Comment by Akagi201** [comment]
@meslahik Did you build it on macOS or Linux? All my codes are tested on macOS.

**Comment by meslahik** [comment]
I built it on my macOS.

**Comment by tyuownu** [comment]
Yeah, same question with @meslahik . Test under ubuntu 16.04 64bit, CMAKE 3.5.1.

**Comment by thulc** [comment]
> Hi, After hours of trying to build to hello-module project, found that according to the documentation for [find_library](https://cmake.org/cmake/help/cmake2.6docs.html#command:find_library) you need to have PATHS rather than PATH to define additional paths for searching for the libraries.

有用的
